workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/mobile_qlgn.xcworkspace"
        XCODE_SCHEME: "mobile_qlgn"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
    artifacts:
      - build/ios/ipa/*.ipa